// MultiQC — aggregate QC reports from all pipeline steps
// Image: quay.io/biocontainers/multiqc:1.22.3--pyhdfd78af_0

process MULTIQC {
    label        'small'
    publishDir   "${params.outdir}/multiqc", mode: params.publish_dir_mode

    container 'quay.io/biocontainers/multiqc:1.22.3--pyhdfd78af_0'

    input:
    path multiqc_files   // all QC files, collected
    path multiqc_config

    output:
    path "multiqc_report.html",   emit: report
    path "multiqc_data/",         emit: data
    path "multiqc_plots/",        emit: plots

    script:
    """
    multiqc \\
        --config ${multiqc_config} \\
        --title "StrainFlow Pipeline QC Report" \\
        --comment "Generated by StrainFlow v${workflow.manifest.version}" \\
        --outdir . \\
        --force \\
        .
    """
}
